
Section "Module"
    Disable "glx"
    Disable "dri"
    Disable "dri2"
    Disable "dri3"
EndSection

Section "Device"
    Identifier  "Card0"
    Driver      "fbdev"
    Option      "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier  "Screen0"
    Device      "Card0"
    DefaultDepth 16
EndSection

Section "InputDevice"
    Identifier  "Keyboard0"
    Driver      "evdev"
    Option      "Device" "/dev/input/event0"
    Option      "XkbLayout" "us"
EndSection

Section "ServerLayout"
    Identifier  "Layout0"
    Screen      "Screen0"
    InputDevice "Keyboard0" "CoreKeyboard"
EndSection
